= Enabling and Disabling Optional Features

The connector offer some optional features that can be enabled or disabled via configuration. This section describes how to do it

== Operator Commissions

By default, the operator commissions feature is enabled. This feature is handled by the `PAYPAL_HYPERWALLET_OPERATOR_COMMISSIONS_ENABLED` configuration variable.

== Financial Reporting

The connector has the ability to generate a financial report, compiling information from the Mirakl and Braintree platforms.

To enable this functionality, you simply need to configure the variables described xref:configuration:configvars/configvars.adoc#configvarsvars-financialreports[here].

== Internal Management APIs

The connector provides HTTP endpoints that allows querying and manipulating some internal data that could help with diagnosing and solving problems. Manipulation of this data could be dangerous, so these endpoints are disabled by default. You can set `PAYPAL_MANAGEMENT_ENABLED` variable to `true` to enable them.

== Http Traffic Logging

The connector provides the ability to log all the http traffic that it generates or receives. This feature is disabled by default. You can enable it by setting the `PAYPAL_HYPERWALLET_HTTP_CAPTURE_ENABLED` variable to `true`. Also, if the management APIs are enabled, you can use them to enable or disable this feature at runtime making a PUT to the endpont `/management/traffic-auditor/configuration`:

....
curl --location --request PUT 'localhost:8080/management/traffic-auditor/configuration' \
--header 'Content-Type: application/json' \
--data '{
    "trafficAuditorEnabled": true
}'
....

[#new-user-mapping]
== New store name and legal name mapping

This feature specifically applies to business shops and determines how the connector maps the business legal name of Hyperwallet users based on the information from Mirakl shops.

The behavior of this feature is controlled by the `PAYPAL_HYPERWALLET_NEW_USER_MAPPING_ENABLED` environment variable. By default, the variable is set to `false``, which means the connector uses the legacy mapping from previous versions. However, for new deployments where *no sellers have been onboarded yet*, we encourage using the new mapping as it is more accurate.

The `PAYPAL_HYPERWALLET_NEW_USER_MAPPING_ENABLED` variable can be set to the following values:

- `false`: The shop name in Mirakl will be mapped to the `businessName` field in Hyperwallet, which represents the business's legal name. The shop's corporate name will be mapped to the `businessOperatingName` field. This is the default behavior.
- `true`: The shop name in Mirakl will be mapped to the `businessOperatingName` field in Hyperwallet, and the corporate name will be mapped to the `businessName` field.

[WARNING]
====
This mapping is important because it affects the KYC verification process, since the business legal name is used to check the validity of some documents.

By default the new store name and legal name mapping is disabled, to ensure compatibililty with existing deployments that have already onboarded sellers.

If this variable changes its value after a seller has been onboarded, when the shop is updated the connector will update the Hyperwallet user changing its business legal name according to the variable new value, triggering a KYC verification process that can fail since the business legal name is different from the previous one.
====
