package com.paypal.notifications.repository;

import com.hyperwallet.clientsdk.model.HyperwalletWebhookNotification;

/**
 * Repository to access notifications previously sent by Hyperwallet via webhooks.
 */
public interface NotificationsRepository {

	/**
	 * Retrieves a notification generated by Hyperwallet.
	 * @param program The program associated to the notification.
	 * @param token The token of the notification.
	 * @return The notification generated by Hyperwallet with the provided token or
	 * <code>null</code> if there is no previously generated notification with that token
	 */
	HyperwalletWebhookNotification getHyperwalletWebhookNotification(String program, String token);

}
