== Features

=== Seller onboarding

|===
|Feature |Connector->Mirakl Actions |Connector->Hyperwallet Actions

|Create payee account for Individual Hyperwallet User
a| * Retrieve shop details from Mirakl for newly onboarded sellers trading as individuals.
* Obtains all shops added to operator marketplace since the previous extract.
* Mirakl shop record updated with generated Hyperwallet User token (Additional Mirakl custom field).
* Assign the shop to a relevant level within the operator program hierarchy (e.g. if the operator works through separate legal entities in different jurisdictions).

a| * Create a new User in Hyperwallet with type of INDIVIDUAL
* One Hyperwallet User created for each newly onboarded Individual seller obtained from Mirakl.
* The shop will be assigned to the corresponding operator program within the merchant program hierarchy in Hyperwallet.

|Create payee account for Business Hyperwallet User

a| * Retrieve shop details from Mirakl for newly onboarded sellers trading as businesses.
* Obtains all shops added to operator marketplace since the previous extract.
* Mirakl shop record updated with generated. Hyperwallet User token (Additional Mirakl custom field).
* Assign the shop to a relevant level within the operator program hierarchy (e.g. if the operator works through separate legal entities in different jurisdictions).

a| * Create a new User in Hyperwallet with type of BUSINESS.
* One Hyperwallet User created for each newly onboarded Business seller obtained from Mirakl.
* The shop will be assigned to the corresponding operator program within the merchant program hierarchy in Hyperwallet.

|Accept Hyperwallet T&Cs
a| * Only retrieve shops that accepted the Hyperwallet T&Cs.

a| * Only shops that have accepted Hyperwallet T&Cs will be sent to Hyperwallet.
* Rejecting the T&Cs means the shop will not be eligible for any of the Hyperwallet features including payout.

|Update existing Hyperwallet Users
a| * Retrieve the details of all existing shops in Mirakl that have been updated since the last extract.
* Custom field containing the Hyperwallet User token indicates the Shop already exists in Hyperwallet.

a| * Update the existing Hyperwallet User with all shop data retrieved from Mirakl.
* The user token will be used to update the relevant Payee record in Hyperwallet.

|Create Bank account
a| * Retrieve bank account details for newly onboarded sellers. The following Mirakl bank account types are supported:
+
- IBAN (EUR, CHF);
- U.S. ABA (USD);
- CANADIAN (CAD, USD);
-  United Kingdom account (GBP).
* Mirakl shop record updated with generated Hyperwallet bank account token (Additional Mirakl custom field).
* *Note:* There is not separate payment method in Mirakl for UK bank accounts, hence this cannot be implemented at this stage.[image]

a| * Bank account (i.e. Transfer Method) created after the User account is successfully created for the seller in Hyperwallet.
* A single bank account created for the existing Hyperwallet User account.
* Bank Account is the only transfer method supported in HMC.

|Update Bank account details
a| * Retrieve the details of bank accounts that have been updated since the last extract.
* Custom field containing the Hyperwallet TRM token indicates the bank account for the shop already exists in Hyperwallet.

a| * Update the existing bank accounts with new details from Mirakl, i.e. update existing Transfer method.

|Configurable seller data extract frequency
a| * Operator can configure the frequency of the shop details/bank account retrieval from Mirakl.

a| * Process to extract shop data from Mirakl is triggered based on configured frequency
|===

=== KYC verification

|===
|Feature |Connector->Mirakl Actions |Connector->Hyperwallet Actions

|KYC status updates
a| * Update Mirakl with KYC status changes received from Hyperwallet via HMC.
* KYC status is displayed as part of the shop record in Mirakl

a| * Receive a notification of changes in KYC status as part of the payee verification process. This will be received by the Connector via a webhook and sent through to Mirakl.

|KYC failure reasons
a| * Send a predefined failure reasons based on the KYC status received.
* Failure reason is displayed as part of the shop record in Mirakl

a| * Receive KYC status update from Hyperwallet
|===

=== Payout

[width="100%",cols="17%,44%,39%",options="header",]
|===
|Feature |Connector->Mirakl Actions |Connector->Hyperwallet Actions

|Payout to sellers
a| * Retrieve details of all seller invoices generated since the last extract.
* Retrieves invoices generated by the Mirakl operator billing cycle, or manual credit notes, that are eligible for payout and:
- have not yet been paid;
- are not in draft state.

a| * Create a payment request for paying out the seller based on the details of the invoice.
* All seller payouts are from a single operator funding account.
* Seller payouts made to the seller bank account stored in Hyperwallet

|Payout to Operator
a| * Retrieve details of the operator commission and subscription fee amounts due for each seller invoice.
* Operators can configure whether to turn off this automated payout process.

a| * Create a new operator payout request to payout the individual commission and subscription fee amounts due to the operator for each seller invoice
* If operator chooses to turn off the automated payout, their commission and subscription will not be processed/paid and will remain in the main funding account in Hyperwallet.
* Send the corresponding program tokens based on which entity/level of merchant hierarchy the seller belongs to.
* Payout will be directed to the corresponding operator bank account associated with the relevant merchant program in Hyperwallet.

|Payout status updates
a| * Send a failure notification to the operator by email in case of a payout failure (seller payout or operator payout).

a| * Payout status will be received by HMC via a webhook.

|===