= API calls

The following API calls are made during the invoice extraction job:

== Invoice extraction
|===
| Call | Target System | Endpoint | Parameters

| Retrieve all pending invoices since the last specified date
| Mirakl
| https://developer.mirakl.com/content/product/mms/rest/front/openapi3/invoicing-and-accounting/sbc11[SBC11 - List seller billing cycles]
a| * `start_date`: date calculated by the job as the starting date since the last job 
execution or the date manually specified in the job execution.
* `pay_out_state`: `TO_PAY`
* `order_by`: `dateCreated asc`

| Create a payment in Hyperwallet
| Hyperwallet
| https://docs.hyperwallet.com/content/api/v4/resources/payments/create[`POST /payments`]
a| A body is generated from the Mirakl Invoice according to the data mapping rules.
The following mappings are specially relevant:

* `clientPaymentId`: field `invoice_id` from Mirakl invoice.
* `amount`: field `amount_transferred_to_seller` from Mirakl seller billing cycle.

| Create an operator payment in Hyperwallet
| Hyperwallet
| `POST /payments`
a| A body is generated from the Mirakl seller billing cycle according to the data mapping rules.
The following mappings are specially relevant:

* `clientPaymentId`: field `id` from Mirakl seller billing cycle plus the suffix `-operatorFee`.
* `amount`: field `amount_transferred_to_operator` from Mirakl seller billing cycle.
|===

== Credit notes extraction

|===
| Call | Target System | Endpoint | Parameters

| Retrieve all pending credit notes since the last specified date
| Mirakl
| https://developer.mirakl.com/content/product/mms/rest/front/openapi3/invoicing-and-accounting/sbc11[SBC11 - List seller billing cycles]
a|
* `start_date`: date calculated by the job as the starting date since the last job 
execution or the date manually specified in the job execution.
* `pay_out_state`: `TO_PAY`
* `order_by`: `dateCreated asc`

| Create a payment in Hyperwallet
| Hyperwallet
| https://docs.hyperwallet.com/content/api/v4/resources/payments/create[`POST /payments`]
a| A body is generated from the Mirakl seller billing cycle according to the data mapping rules.
The following mappings are specially relevant:

* `clientPaymentId`: field `id` from Mirakl seller billing cycle.
* `amount`: field `amount_transferred_to_seller` from Mirakl seller billing cycle.
|===
