package com.paypal.kyc.incomingnotifications.model;

public enum KYCDocumentTypeEnum {

	//@formatter:off
	DRIVERS_LICENSE, GOVERNMENT_ID, PASSPORT, BANK_STATEMENT, CREDIT_CARD_STATEMENT, OFFICIAL_GOVERNMENT_LETTER, PROPERTY_TAX_ASSESSMENT, TAX_RETURN, UTILITY_BILL, INCORPORATION, BUSINESS_REGISTRATION, OPERATING_AGREEMENT
	//@formatter:on

}
