== Payout Notifications 

Payout notifications are received from Hyperwallet via a webhook.

*+++Success notifications+++*

When the payment status is changed to COMPLETED in Hyperwallet HMC will automatically set the status on the corresponding accounting document in Mirakl to PAID.

The payment confirmation is received by the HMC via a Payment webhook notification sent from Hyperwallet, with the status: PAYMENT.UDATED.STATUS.COMPLETED.

In regard to Operator payout, there is no Mirakl end-point for confirming that the operator has had commissions/subscriptions paid out for an invoice. It is assumed that the Hyperwallet platform will be responsible for notifying the operators about successful payouts.

*+++Failure notifications+++*

Handling of failed payout notifications applies to the following statuses received by HMC from Hyperwallet via the webhook:

* FAILED
* RECALLED
* RETURNED

When one of those statuses is received via the webhook, the HMC will send an email to the operator's email address (configured in properties). Below is the content of the email message:

____
_Subject: Payment issue - <invoice ID> +
Body: There was an issue with payment of <invoice ID> invoice. The payment status is <HW STATE>. Please login to Hyperwallet to view and resolve the payment issue._
____

*Note:* <invoice ID> will be provided in the format to distinguish the operator payment (e.g. “12345-operatorFee”).

=== REST API Endpoints

[width="100%",cols="15%,13%,72%",options="header",]
|===
|Platform |Endpoint |Documentation
|Mirakl |(PUT) IV07 |https://help.mirakl.net/help/api-doc/operator/mmp.html#IV07[+++help.mirakl.net/help/api-doc/operator/mmp.html#IV07+++]
|Hyperwallet |Webhook |https://docs.hyperwallet.com/content/webhooks/v1/notification-types/payments[+++docs.hyperwallet.com/content/webhooks/v1/notification-types/payments+++]
|===